import fs from 'node:fs';
import path from 'node:path';
import type { RuntimeRevisionAssetType } from '../config/runtime-config-revisions.js';
import {
  clearRuntimeAssetRevisions,
  syncRuntimeAssetRevisionState,
} from '../config/runtime-config-revisions.js';
import { emitDistillAuditEvent } from './audit.js';
import type { DistillPaths } from './paths.js';
import { readJsonFile } from './paths.js';
import { loadDistillState } from './state.js';
import type { DistillRunRecord } from './types.js';

export interface ForgetSubjectResult {
  removedPaths: string[];
  clearedRevisions: number;
}

/**
 * R20 right-to-be-forgotten: the subject's corpus, persona files, work
 * module, run artefacts, and their F4 revision snapshots are discoverable
 * and removable as one identifier set. The forget action itself is appended
 * to the audit trail before deletion — the hash chain records that erasure
 * happened without retaining what was erased.
 */
export function forgetDistilledSubject(
  paths: DistillPaths,
  confirmedBy: string,
): ForgetSubjectResult {
  const state = loadDistillState(paths);
  const trackedAssets: { file: string; asset: RuntimeRevisionAssetType }[] = [
    { file: paths.corpusDocumentsPath, asset: 'knowledge' },
    { file: path.join(paths.workspaceDir, 'IDENTITY.md'), asset: 'template' },
    { file: path.join(paths.workspaceDir, 'SOUL.md'), asset: 'template' },
    { file: path.join(paths.workspaceDir, 'USER.md'), asset: 'template' },
    { file: path.join(paths.workspaceDir, 'CV.md'), asset: 'cv' },
  ];
  const skillDir = state.skillName
    ? path.join(paths.workspaceDir, 'skills', state.skillName)
    : null;
  if (skillDir && fs.existsSync(skillDir)) {
    for (const file of listFilesRecursive(skillDir)) {
      trackedAssets.push({ file, asset: 'skill' });
    }
  }
  const runDirs = collectSubjectRunDirs(paths);

  emitDistillAuditEvent({
    subject: paths.subject,
    runId: 'forget',
    type: 'distill.subject.forgotten',
    fields: {
      confirmedBy,
      subjectDir: paths.subjectDir,
      trackedAssets: trackedAssets.map((entry) => entry.file),
      runDirs,
    },
  });

  const removedPaths: string[] = [];
  for (const entry of trackedAssets) {
    if (entry.asset === 'template' || entry.asset === 'cv') {
      if (removeIfDistilled(entry.file)) removedPaths.push(entry.file);
    }
  }
  if (skillDir && fs.existsSync(skillDir)) {
    fs.rmSync(skillDir, { recursive: true, force: true });
    removedPaths.push(skillDir);
  }
  for (const runDir of runDirs) {
    fs.rmSync(runDir, { recursive: true, force: true });
    removedPaths.push(runDir);
  }
  if (fs.existsSync(paths.subjectDir)) {
    fs.rmSync(paths.subjectDir, { recursive: true, force: true });
    removedPaths.push(paths.subjectDir);
  }

  // Purge the F4 layer: syncing a now-missing file archives its last content
  // and drops the live state row; clearing then deletes every archive row.
  // Net effect: no generated content survives in the revision database.
  let clearedRevisions = 0;
  for (const entry of trackedAssets) {
    if (!fs.existsSync(entry.file)) {
      syncRuntimeAssetRevisionState(entry.asset, entry.file, {
        actor: 'distill',
        route: 'cli',
        source: 'forget',
      });
    }
    clearedRevisions += clearRuntimeAssetRevisions(entry.asset, entry.file);
  }
  return { removedPaths, clearedRevisions };
}

function collectSubjectRunDirs(paths: DistillPaths): string[] {
  let entries: string[];
  try {
    entries = fs.readdirSync(paths.runsRootDir);
  } catch {
    return [];
  }
  const dirs: string[] = [];
  for (const entry of entries) {
    const runDir = path.join(paths.runsRootDir, entry);
    const run = readJsonFile<DistillRunRecord>(path.join(runDir, 'run.json'));
    if (run?.subject === paths.subject) dirs.push(runDir);
  }
  return dirs;
}

function removeIfDistilled(filePath: string): boolean {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    if (!content.includes('Generated by HybridClaw human distillation')) {
      return false;
    }
    fs.rmSync(filePath, { force: true });
    return true;
  } catch {
    return false;
  }
}

function listFilesRecursive(dir: string): string[] {
  const files: string[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true, recursive: true });
  for (const entry of entries) {
    if (entry.isFile()) files.push(path.join(entry.parentPath, entry.name));
  }
  return files;
}
