import type {
  DistillExtraction,
  ExtractionWorkModule,
  PersonaClaim,
  PersonaDimension,
  SubjectProfile,
} from './types.js';

export const DISTILL_GENERATED_NOTE =
  '<!-- Generated by HybridClaw human distillation. Every claim cites corpus document ids; edit via `hybridclaw coworker` so changes stay versioned. -->';

function cite(evidence: string[]): string {
  return evidence.length > 0 ? ` <!-- ${evidence.join(' ')} -->` : '';
}

function claimsFor(
  claims: PersonaClaim[],
  dimension: PersonaDimension,
): PersonaClaim[] {
  return claims.filter(
    (claim) => claim.dimension === dimension && claim.status === 'standing',
  );
}

function claimLines(claims: PersonaClaim[]): string[] {
  return claims.map((claim) => `- ${claim.claim}${cite(claim.evidence)}`);
}

function claimLinesForDimension(
  claims: PersonaClaim[],
  dimension: PersonaDimension,
): string[] {
  const standing = claimsFor(claims, dimension);
  return standing.length > 0 ? claimLines(standing) : [];
}

function memoryWorkLines(work: ExtractionWorkModule): string[] {
  const lines: string[] = [];
  if (work.scope.length > 0) {
    lines.push(...work.scope.map((entry) => `- Scope: ${entry}`));
  }
  for (const workflow of work.workflows) {
    lines.push(`- Workflow: ${workflow.title}${cite(workflow.evidence)}`);
    for (const step of workflow.steps) {
      lines.push(`  - ${step}`);
    }
  }
  if (work.outputPreferences.length > 0) {
    lines.push(
      ...work.outputPreferences.map(
        (preference) =>
          `- Output preference: ${preference.claim}${cite(preference.evidence)}`,
      ),
    );
  }
  for (const entry of work.knowHow) {
    lines.push(
      `- Know-how: ${entry.topic} - ${entry.notes}${cite(entry.evidence)}`,
    );
  }
  for (const example of work.workedExamples) {
    lines.push(
      `- Worked example: ${example.title} - ${example.approach}${cite(example.evidence)}`,
    );
  }
  return lines;
}

/**
 * Renders into the exact vocabulary the runtime already boots
 * (templates/IDENTITY.md): no parallel persona format.
 */
export function renderIdentityFile(
  profile: SubjectProfile,
  extraction: DistillExtraction,
): string {
  const identity = extraction.identity;
  return [
    '# IDENTITY.md - Who Am I?',
    '',
    `- **Name:** ${identity.name || profile.displayName}`,
    `- **Creature:** ${identity.creature || `Distilled coworker modelled on ${profile.displayName}`}`,
    `- **Vibe:** ${identity.vibe || 'still forming — distilled from source material'}`,
    `- **Emoji:** ${identity.emoji || '🫧'}`,
    '- **Avatar:**',
    '',
    '---',
    '',
    `Distilled from ${profile.displayName}'s source material${profile.role ? ` (${profile.role})` : ''}. I carry their patterns, not their authority — when I am unsure what they would do, I say so instead of guessing.`,
    '',
    DISTILL_GENERATED_NOTE,
    '',
  ].join('\n');
}

export function renderSoulFile(
  profile: SubjectProfile,
  claims: PersonaClaim[],
): string {
  const lines: string[] = [
    '# SOUL.md - Who You Are',
    '',
    `_You are a distilled coworker modelled on ${profile.displayName}. These truths come from their own words and work — every line cites its sources._`,
    '',
    '## Core Truths',
    '',
  ];
  const decision = claimsFor(claims, 'decision-making');
  lines.push(
    ...(decision.length > 0
      ? claimLines(decision)
      : ['- _No decision-making evidence distilled yet._']),
  );
  lines.push('', '## Voice', '');
  const expression = claimsFor(claims, 'expression');
  lines.push(
    ...(expression.length > 0
      ? claimLines(expression)
      : ['- _No expression evidence distilled yet._']),
  );
  lines.push('', '## Working With Others', '');
  const interpersonal = claimsFor(claims, 'interpersonal');
  lines.push(
    ...(interpersonal.length > 0
      ? claimLines(interpersonal)
      : ['- _No interpersonal evidence distilled yet._']),
  );
  const corrections = claimsFor(claims, 'correction');
  if (corrections.length > 0) {
    lines.push('', '## Corrections That Stick', '');
    lines.push(
      `_Explicit corrections from the operator or ${profile.displayName}. These override anything inferred above._`,
      '',
      ...claimLines(corrections),
    );
  }
  lines.push(
    '',
    '## Boundaries',
    '',
    `- You mirror ${profile.displayName}'s judgment, not their identity. Never sign as them or let anyone believe they wrote what you wrote.`,
    '- Stay inside your distilled corpus: when asked about something the source material does not cover, say it is outside what you learned rather than inventing.',
    '- Private source material stays private. Period.',
    '',
    '## Continuity',
    '',
    'Each session, you wake up fresh. These files _are_ your memory. Corrections given in chat should be recorded with `hybridclaw coworker correct` so they persist and feed the next merge.',
    '',
    DISTILL_GENERATED_NOTE,
    '',
  );
  return lines.join('\n');
}

export function renderUserFile(
  profile: SubjectProfile,
  extraction: DistillExtraction,
): string {
  const notes = (extraction.userNotes || []).map((note) => `- ${note}`);
  return [
    '# USER.md - About Your Human',
    '',
    '_Learn about the person you are helping. Update this as you go._',
    '',
    '- **Name:**',
    '- **What to call them:**',
    '- **Email:**',
    '- **Timezone:**',
    '- **Preferred working style:**',
    '- **Boundaries and approvals:**',
    '',
    '## Context',
    '',
    `_(Fill this in as you learn about your operator. You are modelled on ${profile.displayName}; the notes below describe how ${profile.displayName} worked with colleagues, which is your starting point — not a dossier on your operator.)_`,
    '',
    ...(notes.length > 0 ? notes : ['_(none distilled yet)_']),
    '',
    DISTILL_GENERATED_NOTE,
    '',
  ].join('\n');
}

export function renderMemoryFile(
  profile: SubjectProfile,
  claims: PersonaClaim[],
  extraction: DistillExtraction,
  skillName: string | undefined,
): string {
  const factLines = [
    `- Distilled subject: ${profile.displayName}.`,
    ...(profile.role ? [`- Role: ${profile.role}.`] : []),
    ...claimLinesForDimension(claims, 'identity'),
    ...claimLinesForDimension(claims, 'experience'),
    ...(extraction.userNotes || []).map((note) => `- User note: ${note}`),
  ];
  const decisionLines = claimLinesForDimension(claims, 'decision-making');
  const patternLines = [
    ...claimLinesForDimension(claims, 'expression'),
    ...claimLinesForDimension(claims, 'interpersonal'),
    ...claimLinesForDimension(claims, 'correction'),
  ];
  const workLines = [
    ...(skillName
      ? [`- Distilled work module: \`skills/${skillName}/SKILL.md\`.`]
      : []),
    ...memoryWorkLines(extraction.workModule),
  ];

  return [
    '# MEMORY.md - Session Memory',
    '',
    `_Distilled durable memory for the coworker modelled on ${profile.displayName}. This baseline is generated from validated distillation files and keeps source citations in comments._`,
    '',
    '## Facts',
    '',
    ...(factLines.length > 0 ? factLines : ['_(none distilled yet)_']),
    '',
    '## Decisions',
    '',
    ...(decisionLines.length > 0 ? decisionLines : ['_(none distilled yet)_']),
    '',
    '## Patterns',
    '',
    ...(patternLines.length > 0 ? patternLines : ['_(none distilled yet)_']),
    '',
    '## Work',
    '',
    ...(workLines.length > 0 ? workLines : ['_(none distilled yet)_']),
    '',
    '---',
    '',
    'This is the generated distillation baseline. Add new lived memories through normal memory consolidation so they stay separate from the source-derived profile.',
    '',
    DISTILL_GENERATED_NOTE,
    '',
  ].join('\n');
}

export function renderCvFile(
  profile: SubjectProfile,
  claims: PersonaClaim[],
): string {
  const experience = claimsFor(claims, 'experience');
  const identity = claimsFor(claims, 'identity');
  return [
    `# CV — ${profile.displayName} (distilled coworker)`,
    '',
    profile.role ? `**Role:** ${profile.role}` : '',
    '',
    '## Profile',
    '',
    ...(identity.length > 0
      ? claimLines(identity)
      : ['- _No identity evidence distilled yet._']),
    '',
    '## Experience',
    '',
    ...(experience.length > 0
      ? claimLines(experience)
      : ['- _No experience evidence distilled yet._']),
    '',
    DISTILL_GENERATED_NOTE,
    '',
  ]
    .filter((line, index, all) => line !== '' || all[index - 1] !== '')
    .join('\n');
}

export interface RenderedWorkModule {
  skillName: string;
  files: Record<string, string>;
}

/**
 * The work module is a real skill bundle: R48-parsable frontmatter, the
 * skill-creator progressive-disclosure shape (SKILL.md + references/), and
 * worked examples that carry the subject's judgment with citations.
 */
export function renderWorkModule(
  profile: SubjectProfile,
  extraction: DistillExtraction,
  version: string,
): RenderedWorkModule {
  const work = extraction.workModule;
  const skillName = work.skillName || `${profile.alias}-playbook`;
  const description =
    work.description ||
    `Work the way ${profile.displayName} works: their scope, workflows, and judgment, distilled from source material.`;

  const skillLines: string[] = [
    '---',
    `name: ${skillName}`,
    `description: ${description}`,
    'user-invocable: true',
    'metadata:',
    '  hybridclaw:',
    '    category: productivity',
    `    short_description: "Distilled work module for ${profile.displayName}."`,
    '    tags:',
    '      - coworker',
    '      - distilled',
    '    manifest:',
    `      id: ${skillName}`,
    `      version: ${version}`,
    '      capabilities:',
    ...(work.scope.length > 0
      ? work.scope.map((entry) => `        - ${JSON.stringify(entry)}`)
      : ['        - "distilled-coworker"']),
    '---',
    '',
    `# ${profile.displayName} — Work Module`,
    '',
    `How ${profile.displayName} actually works, distilled from their source material. Every workflow and preference cites the corpus documents it came from.`,
    '',
    '## Scope',
    '',
    ...(work.scope.length > 0
      ? work.scope.map((entry) => `- ${entry}`)
      : ['- _No scope evidence distilled yet._']),
    '',
    '## Workflows',
    '',
  ];
  if (work.workflows.length > 0) {
    for (const workflow of work.workflows) {
      skillLines.push(`### ${workflow.title}${cite(workflow.evidence)}`, '');
      workflow.steps.forEach((step, index) => {
        skillLines.push(`${index + 1}. ${step}`);
      });
      skillLines.push('');
    }
  } else {
    skillLines.push('- _No workflow evidence distilled yet._', '');
  }
  skillLines.push('## Output Preferences', '');
  skillLines.push(
    ...(work.outputPreferences.length > 0
      ? work.outputPreferences.map(
          (preference) => `- ${preference.claim}${cite(preference.evidence)}`,
        )
      : ['- _No output-preference evidence distilled yet._']),
  );
  skillLines.push(
    '',
    '## Deeper Material',
    '',
    '- `references/know-how.md` — domain knowledge mined from source',
    '- `references/worked-examples.md` — how representative tasks were actually handled',
    '',
    '## Limits',
    '',
    `- This module carries ${profile.displayName}'s patterns, not live knowledge. Treat post-distillation events as unknown.`,
    '- When a task falls outside the scope above, say so rather than improvising in their name.',
    '',
    DISTILL_GENERATED_NOTE,
    '',
  );

  const knowHowLines: string[] = [`# Know-How — ${profile.displayName}`, ''];
  if (work.knowHow.length > 0) {
    for (const entry of work.knowHow) {
      knowHowLines.push(
        `## ${entry.topic}${cite(entry.evidence)}`,
        '',
        entry.notes,
        '',
      );
    }
  } else {
    knowHowLines.push('_No know-how evidence distilled yet._', '');
  }

  const exampleLines: string[] = [
    `# Worked Examples — ${profile.displayName}`,
    '',
    '_Representative tasks and how they were actually handled, mined from source material._',
    '',
  ];
  if (work.workedExamples.length > 0) {
    for (const example of work.workedExamples) {
      exampleLines.push(
        `## ${example.title}${cite(example.evidence)}`,
        '',
        `**Situation:** ${example.situation}`,
        '',
        `**Approach:** ${example.approach}`,
        '',
      );
      if (example.outcome) {
        exampleLines.push(`**Outcome:** ${example.outcome}`, '');
      }
    }
  } else {
    exampleLines.push('_No worked examples distilled yet._', '');
  }

  return {
    skillName,
    files: {
      'SKILL.md': skillLines.join('\n'),
      'references/know-how.md': knowHowLines.join('\n'),
      'references/worked-examples.md': exampleLines.join('\n'),
    },
  };
}
