import fs from 'node:fs';
import path from 'node:path';

import { displayNameForAgent, getAgentById } from '../agents/agent-registry.js';
import { getRuntimeConfig } from '../config/runtime-config.js';
import { agentWorkspaceDir } from '../infra/ipc.js';
import { logger } from '../logger.js';
import { callAuxiliaryModel } from '../providers/auxiliary.js';
import {
  findCheapestModelMeetingCapabilities,
  getModelCatalogMetadata,
} from '../providers/model-catalog.js';
import {
  isAuxiliaryTaskDisabled,
  normalizeAuxiliaryProviderModel,
} from '../providers/task-routing.js';
import {
  type ConfidentialPlaceholderMap,
  createPlaceholderMap,
  dehydrateConfidential,
} from '../security/confidential-redact.js';
import type { ConfidentialRuleSet } from '../security/confidential-rules.js';
import {
  getConfidentialRuleSet,
  isConfidentialRedactionEnabled,
} from '../security/confidential-runtime.js';
import { redactSecrets } from '../security/redact.js';
import { formatDurationMs } from '../utils/text-format.js';
import { isRecord } from '../utils/type-guards.js';
import type { SkillRunEvent } from './skill-run-events.js';

const GENERATED_CV_MARKER = '<!-- Generated by HybridClaw agent CV. -->';
const AGENT_CV_STATE_SCHEMA_VERSION = 1;
const CV_STATE_FILE = '.CV.state.json';
const MAX_NARRATION_SOURCE_CHARS = 1_200;
const DEFAULT_CV_NARRATION_MAX_TOKENS = 1_200;
const DEFAULT_CV_NARRATION_TIMEOUT_MS = 20_000;
const APPROX_CHARS_PER_TOKEN = 4;

interface AgentCvEntry {
  run_id: string;
  session_id: string;
  skill_id: string;
  date: string;
  created_at: string;
  outcome: SkillRunEvent['outcome'];
  title: string;
  description: string;
}

interface AgentCvState {
  schema_version: typeof AGENT_CV_STATE_SCHEMA_VERSION;
  agent_id: string;
  updated_at: string;
  last_rendered_at: string | null;
  narration_cost_usd_by_day: Record<string, number>;
  entries: AgentCvEntry[];
}

interface CvNarration {
  run_id: string;
  title: string;
  description: string;
}

const pendingAgentCvRefreshes = new Map<string, NodeJS.Timeout>();
const pendingAgentCvRenderRefreshes = new Map<string, NodeJS.Timeout>();
const pendingAgentCvEvents = new Map<string, Map<string, SkillRunEvent>>();
const queuedAgentCvRefreshWork = new Map<string, Promise<void>>();

export function cvPathForAgent(agentId: string): string {
  return path.join(agentWorkspaceDir(agentId), 'CV.md');
}

function cvStatePathForAgent(agentId: string): string {
  return path.join(agentWorkspaceDir(agentId), CV_STATE_FILE);
}

function emptyCvState(agentId: string): AgentCvState {
  return {
    schema_version: AGENT_CV_STATE_SCHEMA_VERSION,
    agent_id: agentId,
    updated_at: new Date().toISOString(),
    last_rendered_at: null,
    narration_cost_usd_by_day: {},
    entries: [],
  };
}

function normalizeCvEntry(value: unknown): AgentCvEntry | null {
  if (!isRecord(value)) return null;
  const str = (key: string) =>
    typeof value[key] === 'string' ? value[key].trim() : '';
  const runId = str('run_id');
  const sessionId = str('session_id');
  const skillId = str('skill_id');
  const date = str('date');
  const createdAt = str('created_at');
  const title = str('title');
  const description = str('description');
  const outcome =
    value.outcome === 'success' ||
    value.outcome === 'partial' ||
    value.outcome === 'failure'
      ? value.outcome
      : null;
  if (
    !runId ||
    !sessionId ||
    !skillId ||
    !date ||
    !createdAt ||
    !title ||
    !outcome
  ) {
    return null;
  }
  return {
    run_id: runId,
    session_id: sessionId,
    skill_id: skillId,
    date,
    created_at: createdAt,
    outcome,
    title,
    description: description || title,
  };
}

function normalizeCostMap(value: unknown): Record<string, number> {
  if (!isRecord(value)) return {};
  const normalized: Record<string, number> = {};
  for (const [day, rawCost] of Object.entries(value)) {
    const normalizedDay = day.trim();
    const cost = typeof rawCost === 'number' ? rawCost : Number(rawCost);
    if (!/^\d{4}-\d{2}-\d{2}$/.test(normalizedDay)) continue;
    if (!Number.isFinite(cost) || cost < 0) continue;
    normalized[normalizedDay] = cost;
  }
  return normalized;
}

function quarantineCorruptCvState(input: {
  agentId: string;
  statePath: string;
  error: unknown;
}): void {
  const corruptPath = `${input.statePath}.corrupt-${Date.now()}`;
  try {
    fs.renameSync(input.statePath, corruptPath);
    logger.warn(
      {
        agentId: input.agentId,
        statePath: input.statePath,
        corruptPath,
        error: input.error,
      },
      'Quarantined corrupt agent CV state',
    );
  } catch (quarantineError) {
    logger.warn(
      {
        agentId: input.agentId,
        statePath: input.statePath,
        error: input.error,
        quarantineError,
      },
      'Failed to quarantine corrupt agent CV state',
    );
  }
}

function loadCvState(agentId: string): AgentCvState {
  const statePath = cvStatePathForAgent(agentId);
  if (!fs.existsSync(statePath)) return emptyCvState(agentId);
  try {
    const parsed = JSON.parse(fs.readFileSync(statePath, 'utf-8')) as unknown;
    if (!isRecord(parsed)) {
      quarantineCorruptCvState({
        agentId,
        statePath,
        error: new Error('Agent CV state root must be an object.'),
      });
      return emptyCvState(agentId);
    }
    const entries = Array.isArray(parsed.entries)
      ? parsed.entries
          .map(normalizeCvEntry)
          .filter((entry): entry is AgentCvEntry => Boolean(entry))
      : [];
    return {
      schema_version: AGENT_CV_STATE_SCHEMA_VERSION,
      agent_id: agentId,
      updated_at:
        typeof parsed.updated_at === 'string'
          ? parsed.updated_at
          : new Date().toISOString(),
      last_rendered_at:
        typeof parsed.last_rendered_at === 'string'
          ? parsed.last_rendered_at
          : null,
      narration_cost_usd_by_day: normalizeCostMap(
        parsed.narration_cost_usd_by_day,
      ),
      entries,
    };
  } catch (error) {
    quarantineCorruptCvState({ agentId, statePath, error });
    return emptyCvState(agentId);
  }
}

function writeFileAtomic(
  filePath: string,
  content: string,
  options?: fs.WriteFileOptions,
): void {
  const dir = path.dirname(filePath);
  const tempPath = path.join(
    dir,
    `${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`,
  );
  fs.mkdirSync(dir, { recursive: true });
  try {
    fs.writeFileSync(tempPath, content, options);
    fs.renameSync(tempPath, filePath);
  } catch (error) {
    if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
    throw error;
  }
}

async function writeFileAtomicAsync(
  filePath: string,
  content: string,
  options?: fs.WriteFileOptions,
): Promise<void> {
  const dir = path.dirname(filePath);
  const tempPath = path.join(
    dir,
    `${path.basename(filePath)}.${process.pid}.${Date.now()}.tmp`,
  );
  await fs.promises.mkdir(dir, { recursive: true });
  try {
    await fs.promises.writeFile(tempPath, content, options);
    await fs.promises.rename(tempPath, filePath);
  } catch (error) {
    try {
      await fs.promises.unlink(tempPath);
    } catch {
      // Best-effort cleanup after a failed atomic write.
    }
    throw error;
  }
}

function writeJsonAtomic(filePath: string, value: unknown): void {
  writeFileAtomic(filePath, `${JSON.stringify(value, null, 2)}\n`, {
    encoding: 'utf-8',
    mode: 0o600,
  });
}

async function writeJsonAtomicAsync(
  filePath: string,
  value: unknown,
): Promise<void> {
  await writeFileAtomicAsync(filePath, `${JSON.stringify(value, null, 2)}\n`, {
    encoding: 'utf-8',
    mode: 0o600,
  });
}

function writeMarkdownAtomic(filePath: string, content: string): void {
  writeFileAtomic(filePath, content, {
    encoding: 'utf-8',
    mode: 0o600,
  });
}

async function writeMarkdownAtomicAsync(
  filePath: string,
  content: string,
): Promise<void> {
  await writeFileAtomicAsync(filePath, content, {
    encoding: 'utf-8',
    mode: 0o600,
  });
}

function sortCvEntries(entries: AgentCvEntry[]): AgentCvEntry[] {
  return [...entries].sort(
    (left, right) =>
      right.date.localeCompare(left.date) ||
      right.created_at.localeCompare(left.created_at) ||
      right.run_id.localeCompare(left.run_id),
  );
}

function retentionCutoffDate(retentionDays: number, now: Date): string | null {
  if (retentionDays <= 0) return null;
  return new Date(now.getTime() - retentionDays * 24 * 60 * 60 * 1000)
    .toISOString()
    .slice(0, 10);
}

function splitEntriesByRetention(input: {
  entries: AgentCvEntry[];
  retentionDays: number;
  now: Date;
}): { recent: AgentCvEntry[]; olderByYear: Map<string, AgentCvEntry[]> } {
  const cutoff = retentionCutoffDate(input.retentionDays, input.now);
  const recent: AgentCvEntry[] = [];
  const olderByYear = new Map<string, AgentCvEntry[]>();
  for (const entry of sortCvEntries(input.entries)) {
    if (!cutoff || entry.date >= cutoff) {
      recent.push(entry);
      continue;
    }
    const year = entry.date.slice(0, 4);
    const existing = olderByYear.get(year) || [];
    existing.push(entry);
    olderByYear.set(year, existing);
  }
  return { recent, olderByYear };
}

function pruneCvEntriesByRetention(
  entries: AgentCvEntry[],
  retentionDays: number,
  now: Date,
): AgentCvEntry[] {
  const cutoff = retentionCutoffDate(retentionDays, now);
  if (!cutoff) return sortCvEntries(entries);
  return sortCvEntries(entries.filter((entry) => entry.date >= cutoff));
}

function renderYearSummary(entries: AgentCvEntry[]): string {
  const titles = entries.slice(0, 3).map((entry) => entry.title);
  const suffix =
    entries.length > titles.length
      ? `, and ${entries.length - titles.length} more`
      : '';
  return `Completed ${entries.length} earlier assignment${entries.length === 1 ? '' : 's'}: ${titles.join('; ')}${suffix}.`;
}

function renderCvMarkdown(input: {
  displayName: string;
  state: AgentCvState;
  generatedAt: string;
  retentionDays: number;
}): string {
  const now = new Date(input.generatedAt);
  const { recent, olderByYear } = splitEntriesByRetention({
    entries: input.state.entries,
    retentionDays: input.retentionDays,
    now: Number.isNaN(now.getTime()) ? new Date() : now,
  });
  const lines = [GENERATED_CV_MARKER, `# ${input.displayName} — CV`, ''];

  if (recent.length === 0 && olderByYear.size === 0) {
    lines.push('No completed assignments recorded yet.');
  } else {
    for (const entry of recent) {
      lines.push(
        `## ${entry.date} — ${entry.title}`,
        '',
        entry.description,
        '',
      );
    }
    for (const [year, entries] of [...olderByYear.entries()].sort((a, b) =>
      b[0].localeCompare(a[0]),
    )) {
      lines.push(`## ${year} Summary`, '', renderYearSummary(entries), '');
    }
  }

  return `${lines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()}\n`;
}

export function cv(
  agentId: string,
  options?: { generatedAt?: string },
): string {
  const normalizedAgentId = agentId.trim();
  if (!normalizedAgentId) {
    throw new Error('Agent id is required.');
  }
  const state = loadCvState(normalizedAgentId);
  const config = getRuntimeConfig().adaptiveSkills.cv;
  return renderCvMarkdown({
    displayName: displayNameForAgent(normalizedAgentId),
    state,
    generatedAt: options?.generatedAt || new Date().toISOString(),
    retentionDays: config.retentionDays,
  });
}

export function refreshAgentCv(agentId: string): string | null {
  const normalizedAgentId = agentId.trim();
  if (!normalizedAgentId) return null;
  if (!getAgentById(normalizedAgentId)) return null;
  const state = loadCvState(normalizedAgentId);
  const now = new Date().toISOString();
  const nextState = { ...state, updated_at: now, last_rendered_at: now };
  renderPersistedAgentCv(normalizedAgentId, nextState, now);
  return cvPathForAgent(normalizedAgentId);
}

function renderPersistedAgentCv(
  agentId: string,
  state: AgentCvState,
  generatedAt: string,
): void {
  const pendingRender = pendingAgentCvRenderRefreshes.get(agentId);
  if (pendingRender) {
    clearTimeout(pendingRender);
    pendingAgentCvRenderRefreshes.delete(agentId);
  }
  writeJsonAtomic(cvStatePathForAgent(agentId), state);
  writeMarkdownAtomic(
    cvPathForAgent(agentId),
    renderCvMarkdown({
      displayName: displayNameForAgent(agentId),
      state,
      generatedAt,
      retentionDays: getRuntimeConfig().adaptiveSkills.cv.retentionDays,
    }),
  );
}

async function renderPersistedAgentCvAsync(
  agentId: string,
  state: AgentCvState,
  generatedAt: string,
): Promise<void> {
  const pendingRender = pendingAgentCvRenderRefreshes.get(agentId);
  if (pendingRender) {
    clearTimeout(pendingRender);
    pendingAgentCvRenderRefreshes.delete(agentId);
  }
  await writeJsonAtomicAsync(cvStatePathForAgent(agentId), state);
  await writeMarkdownAtomicAsync(
    cvPathForAgent(agentId),
    renderCvMarkdown({
      displayName: displayNameForAgent(agentId),
      state,
      generatedAt,
      retentionDays: getRuntimeConfig().adaptiveSkills.cv.retentionDays,
    }),
  );
}

function scrubCvNarrationValue(
  value: unknown,
  mappings: ConfidentialPlaceholderMap,
  ruleSet: ConfidentialRuleSet | null,
): unknown {
  if (typeof value === 'string') {
    const scrubbed = ruleSet
      ? dehydrateConfidential(value, ruleSet, mappings).text
      : value;
    return redactSecrets(scrubbed);
  }
  if (Array.isArray(value)) {
    return value.map((entry) =>
      scrubCvNarrationValue(entry, mappings, ruleSet),
    );
  }
  if (!value || typeof value !== 'object') return value;
  const next: Record<string, unknown> = {};
  for (const [key, entry] of Object.entries(value)) {
    next[key] = scrubCvNarrationValue(entry, mappings, ruleSet);
  }
  return next;
}

function limitText(value: string, maxChars: number): string {
  if (value.length <= maxChars) return value;
  return `${value.slice(0, maxChars)}...`;
}

function narrationSourceForEvent(
  event: SkillRunEvent,
): Record<string, unknown> {
  const ruleSet = isConfidentialRedactionEnabled()
    ? getConfidentialRuleSet()
    : null;
  const mappings = createPlaceholderMap();
  return scrubCvNarrationValue(
    {
      run_id: event.run_id,
      skill_id: event.skill_id,
      outcome: event.outcome,
      latency: formatDurationMs(event.latency_ms),
      input: event.input?.content
        ? limitText(event.input.content, MAX_NARRATION_SOURCE_CHARS)
        : null,
      output: event.output?.content
        ? limitText(event.output.content, MAX_NARRATION_SOURCE_CHARS)
        : null,
      tools: event.tool_executions.map((tool) => ({
        name: tool.name,
        is_error: tool.is_error,
        blocked: tool.blocked,
      })),
      errors: event.errors.slice(0, 3),
    },
    mappings,
    ruleSet,
  ) as Record<string, unknown>;
}

function fallbackNarration(event: SkillRunEvent): CvNarration {
  return {
    run_id: event.run_id,
    title: `Completed ${event.skill_id}`,
    description: `Completed ${event.skill_id} in ${formatDurationMs(event.latency_ms)}.`,
  };
}

function normalizeNarrationText(value: unknown, fallback: string): string {
  const normalized = typeof value === 'string' ? value.trim() : '';
  return limitText(normalized.replace(/\s+/g, ' '), 500) || fallback;
}

function stripJsonFence(value: string): string {
  const trimmed = value.trim();
  const fenced = /^```(?:json)?\s*([\s\S]*?)\s*```$/i.exec(trimmed);
  return fenced?.[1]?.trim() || trimmed;
}

function parseNarrations(
  content: string,
  events: SkillRunEvent[],
): CvNarration[] {
  try {
    const parsed = JSON.parse(stripJsonFence(content)) as unknown;
    const rows = Array.isArray(parsed)
      ? parsed
      : isRecord(parsed) && Array.isArray(parsed.entries)
        ? parsed.entries
        : [];
    const fallbackByRunId = new Map(
      events.map((event) => [event.run_id, fallbackNarration(event)]),
    );
    return rows
      .map((row) => {
        if (!isRecord(row)) return null;
        const runId = typeof row.run_id === 'string' ? row.run_id.trim() : '';
        const fallback = fallbackByRunId.get(runId);
        if (!runId || !fallback) return null;
        return {
          run_id: runId,
          title: normalizeNarrationText(row.title, fallback.title),
          description: normalizeNarrationText(
            row.description,
            fallback.description,
          ),
        };
      })
      .filter((entry): entry is CvNarration => Boolean(entry));
  } catch (error) {
    logger.warn(
      { eventCount: events.length, error },
      'Failed to parse agent CV narration JSON',
    );
    return [];
  }
}

function estimateTokenCount(text: string): number {
  return Math.max(1, Math.ceil(text.length / APPROX_CHARS_PER_TOKEN));
}

function estimateNarrationCostUsd(input: {
  model: string;
  systemPrompt: string;
  userPrompt: string;
  maxOutputTokens: number;
}): number | null {
  const pricing = getModelCatalogMetadata(input.model).pricingUsdPerToken;
  if (pricing.input == null && pricing.output == null) return null;
  const inputPrice = pricing.input ?? pricing.output ?? 0;
  const outputPrice = pricing.output ?? pricing.input ?? 0;
  return (
    estimateTokenCount(input.systemPrompt) * inputPrice +
    estimateTokenCount(input.userPrompt) * inputPrice +
    input.maxOutputTokens * outputPrice
  );
}

function normalizeUsageCostUsd(value: unknown): number | null {
  const cost = typeof value === 'number' ? value : Number(value);
  if (!Number.isFinite(cost) || cost < 0) return null;
  return cost;
}

function configuredCvNarrationModelForBudget(): string | null {
  const config = getRuntimeConfig().auxiliaryModels.cv_narration;
  const model = config.model.trim();
  if (config.provider === 'disabled') return null;
  if (config.provider === 'auto') return model || null;
  try {
    return normalizeAuxiliaryProviderModel({
      provider: config.provider,
      model,
    });
  } catch (error) {
    logger.warn(
      { provider: config.provider, model, error },
      'Failed to normalize configured agent CV narration model',
    );
    return null;
  }
}

async function narrateSkillRuns(input: {
  events: SkillRunEvent[];
  remainingBudgetUsd: number;
}): Promise<{ narrations: CvNarration[]; costUsd: number }> {
  const events = input.events;
  const fallbackModel = findCheapestModelMeetingCapabilities({
    jsonMode: true,
  });
  if (!fallbackModel || input.remainingBudgetUsd <= 0) {
    return { narrations: events.map(fallbackNarration), costUsd: 0 };
  }
  if (isAuxiliaryTaskDisabled('cv_narration')) {
    return { narrations: events.map(fallbackNarration), costUsd: 0 };
  }

  const sources = events.map(narrationSourceForEvent);
  const systemPrompt = [
    'You write concise chronological CV entries for completed AI-agent assignments.',
    'Return JSON only: an array of objects with run_id, title, and description.',
    'Titles must be short past-tense assignment summaries.',
    'Descriptions must be one or two plain sentences.',
    'Do not include PII, secrets, tokens, or credentials.',
  ].join(' ');
  const userPrompt = [
    'Create CV entries for these skill runs.',
    JSON.stringify(sources),
  ].join('\n\n');
  const budgetModel = configuredCvNarrationModelForBudget() || fallbackModel;
  const estimatedCostUsd = estimateNarrationCostUsd({
    model: budgetModel,
    systemPrompt,
    userPrompt,
    maxOutputTokens: DEFAULT_CV_NARRATION_MAX_TOKENS,
  });
  if (estimatedCostUsd == null) {
    logger.warn(
      {
        eventCount: events.length,
        model: budgetModel,
        remainingBudgetUsd: input.remainingBudgetUsd,
      },
      'Skipping agent CV narration because model pricing is unavailable',
    );
    return { narrations: events.map(fallbackNarration), costUsd: 0 };
  }
  if (estimatedCostUsd > input.remainingBudgetUsd) {
    logger.warn(
      {
        eventCount: events.length,
        model: budgetModel,
        estimatedCostUsd,
        remainingBudgetUsd: input.remainingBudgetUsd,
      },
      'Skipping agent CV narration because the daily budget would be exceeded',
    );
    return { narrations: events.map(fallbackNarration), costUsd: 0 };
  }

  try {
    const result = await callAuxiliaryModel({
      task: 'cv_narration',
      fallbackModel,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      maxTokens: DEFAULT_CV_NARRATION_MAX_TOKENS,
      temperature: 0,
      timeoutMs: DEFAULT_CV_NARRATION_TIMEOUT_MS,
    });
    const parsed = parseNarrations(result.content, events);
    const parsedByRunId = new Map(parsed.map((entry) => [entry.run_id, entry]));
    return {
      narrations: events.map(
        (event) => parsedByRunId.get(event.run_id) || fallbackNarration(event),
      ),
      costUsd: normalizeUsageCostUsd(result.usage?.costUsd) ?? estimatedCostUsd,
    };
  } catch (error) {
    logger.warn(
      { eventCount: events.length, error },
      'Failed to narrate agent CV entries',
    );
    return { narrations: events.map(fallbackNarration), costUsd: 0 };
  }
}

function buildEntriesFromNarrations(
  events: SkillRunEvent[],
  narrations: CvNarration[],
): AgentCvEntry[] {
  const narrationByRunId = new Map(
    narrations.map((narration) => [narration.run_id, narration]),
  );
  return events.map((event) => {
    const narration =
      narrationByRunId.get(event.run_id) || fallbackNarration(event);
    return {
      run_id: event.run_id,
      session_id: event.session_id,
      skill_id: event.skill_id,
      date: event.created_at.slice(0, 10),
      created_at: event.created_at,
      outcome: event.outcome,
      title: narration.title,
      description: narration.description,
    };
  });
}

function shouldRenderCv(input: {
  state: AgentCvState;
  now: Date;
  throttleMs: number;
  force?: boolean;
}): boolean {
  if (input.force) return true;
  if (!input.state.last_rendered_at) return true;
  const lastRenderedAtMs = new Date(input.state.last_rendered_at).getTime();
  if (Number.isNaN(lastRenderedAtMs)) return true;
  return input.now.getTime() - lastRenderedAtMs >= input.throttleMs;
}

function isCompletedCvEvent(event: SkillRunEvent): boolean {
  return event.outcome === 'success';
}

function cvNarrationBudgetDay(now: Date): string {
  return now.toISOString().slice(0, 10);
}

function offsetBudgetDay(day: string, offsetDays: number): string {
  const [year = 0, month = 1, date = 1] = day.split('-').map(Number);
  const utcDate = new Date(Date.UTC(year, month - 1, date));
  utcDate.setUTCDate(utcDate.getUTCDate() + offsetDays);
  return utcDate.toISOString().slice(0, 10);
}

function pruneNarrationCostsByDay(
  costs: Record<string, number>,
  currentDay: string,
): Record<string, number> {
  const retentionDays = getRuntimeConfig().adaptiveSkills.cv.retentionDays;
  if (!Number.isFinite(retentionDays) || retentionDays <= 0) return {};

  const earliestDayToKeep = offsetBudgetDay(
    currentDay,
    -(Math.floor(retentionDays) - 1),
  );
  return Object.fromEntries(
    Object.entries(costs).filter(
      ([day]) => day >= earliestDayToKeep && day <= currentDay,
    ),
  );
}

function addNarrationCost(input: {
  costs: Record<string, number>;
  day: string;
  costUsd: number;
}): Record<string, number> {
  const costs =
    input.costUsd <= 0
      ? { ...input.costs }
      : {
          ...input.costs,
          [input.day]: (input.costs[input.day] || 0) + input.costUsd,
        };
  return pruneNarrationCostsByDay(costs, input.day);
}

async function refreshAgentCvFromEvents(input: {
  agentId: string;
  events: SkillRunEvent[];
  forceRender?: boolean;
}): Promise<void> {
  const agentId = input.agentId.trim();
  if (!agentId || !getAgentById(agentId)) return;

  const state = loadCvState(agentId);
  const knownRunIds = new Set(state.entries.map((entry) => entry.run_id));
  const events = input.events.filter(
    (event) => isCompletedCvEvent(event) && !knownRunIds.has(event.run_id),
  );
  if (events.length === 0 && !input.forceRender) return;

  const now = new Date();
  const budgetDay = cvNarrationBudgetDay(now);
  const spentToday = state.narration_cost_usd_by_day[budgetDay] || 0;
  const narrationResult =
    events.length > 0
      ? await narrateSkillRuns({
          events,
          remainingBudgetUsd: Math.max(
            0,
            getRuntimeConfig().adaptiveSkills.cv.narrationDailyBudgetUsd -
              spentToday,
          ),
        })
      : { narrations: [], costUsd: 0 };
  const nextState: AgentCvState = {
    ...state,
    updated_at: now.toISOString(),
    narration_cost_usd_by_day: addNarrationCost({
      costs: state.narration_cost_usd_by_day,
      day: budgetDay,
      costUsd: narrationResult.costUsd,
    }),
    entries: pruneCvEntriesByRetention(
      [
        ...state.entries,
        ...buildEntriesFromNarrations(events, narrationResult.narrations),
      ],
      getRuntimeConfig().adaptiveSkills.cv.retentionDays,
      now,
    ),
  };

  const config = getRuntimeConfig().adaptiveSkills.cv;
  if (
    shouldRenderCv({
      state: nextState,
      now,
      throttleMs: config.renderThrottleMs,
      force: input.forceRender,
    })
  ) {
    nextState.last_rendered_at = now.toISOString();
    await renderPersistedAgentCvAsync(agentId, nextState, now.toISOString());
    return;
  }

  if (nextState.last_rendered_at) {
    const remainingMs =
      config.renderThrottleMs -
      (now.getTime() - new Date(nextState.last_rendered_at).getTime());
    if (remainingMs > 0 && !pendingAgentCvRenderRefreshes.has(agentId)) {
      const timer = setTimeout(() => {
        pendingAgentCvRenderRefreshes.delete(agentId);
        queueAgentCvRefresh(agentId, [], true);
      }, remainingMs);
      timer.unref?.();
      pendingAgentCvRenderRefreshes.set(agentId, timer);
    }
  }
  await writeJsonAtomicAsync(cvStatePathForAgent(agentId), nextState);
}

function queueAgentCvRefresh(
  agentId: string,
  events: SkillRunEvent[],
  forceRender = false,
): void {
  const previous = queuedAgentCvRefreshWork.get(agentId) || Promise.resolve();
  const next = previous
    .then(() => refreshAgentCvFromEvents({ agentId, events, forceRender }))
    .catch((error) => {
      logger.warn({ agentId, error }, 'Failed to refresh agent CV');
    })
    .finally(() => {
      if (queuedAgentCvRefreshWork.get(agentId) === next) {
        queuedAgentCvRefreshWork.delete(agentId);
      }
    });
  queuedAgentCvRefreshWork.set(agentId, next);
}

export function scheduleAgentCvRefresh(
  agentId: string,
  options?: { delayMs?: number; event?: SkillRunEvent },
): boolean {
  const normalizedAgentId = agentId.trim();
  if (!normalizedAgentId) return false;
  if (!getAgentById(normalizedAgentId)) return false;
  if (options?.event) {
    const pending =
      pendingAgentCvEvents.get(normalizedAgentId) ||
      new Map<string, SkillRunEvent>();
    pending.set(options.event.run_id, options.event);
    pendingAgentCvEvents.set(normalizedAgentId, pending);
  }

  const existingTimer = pendingAgentCvRefreshes.get(normalizedAgentId);
  if (existingTimer) clearTimeout(existingTimer);
  const configDelay = getRuntimeConfig().adaptiveSkills.cv.batchDebounceMs;
  const delayMs = Math.max(0, Math.trunc(options?.delayMs ?? configDelay));
  const timer = setTimeout(() => {
    pendingAgentCvRefreshes.delete(normalizedAgentId);
    const events = [
      ...(pendingAgentCvEvents.get(normalizedAgentId) || []).values(),
    ];
    pendingAgentCvEvents.delete(normalizedAgentId);
    queueAgentCvRefresh(normalizedAgentId, events);
  }, delayMs);
  timer.unref?.();
  pendingAgentCvRefreshes.set(normalizedAgentId, timer);
  return true;
}

export async function waitForQueuedAgentCvRefreshes(options?: {
  includeDeferredRenders?: boolean;
}): Promise<void> {
  const agentIds = [...pendingAgentCvRefreshes.keys()];
  for (const agentId of agentIds) {
    const timer = pendingAgentCvRefreshes.get(agentId);
    if (timer) {
      clearTimeout(timer);
      pendingAgentCvRefreshes.delete(agentId);
      const events = [...(pendingAgentCvEvents.get(agentId) || []).values()];
      pendingAgentCvEvents.delete(agentId);
      queueAgentCvRefresh(agentId, events);
    }
  }
  if (options?.includeDeferredRenders !== false) {
    const renderAgentIds = [...pendingAgentCvRenderRefreshes.keys()];
    for (const agentId of renderAgentIds) {
      const timer = pendingAgentCvRenderRefreshes.get(agentId);
      if (timer) {
        clearTimeout(timer);
        pendingAgentCvRenderRefreshes.delete(agentId);
        queueAgentCvRefresh(agentId, [], true);
      }
    }
  }
  await Promise.all([...queuedAgentCvRefreshWork.values()]);
}

export function refreshAgentCvForSkillRun(event: SkillRunEvent): void {
  if (!event.agent_id) return;
  if (!isCompletedCvEvent(event)) return;
  scheduleAgentCvRefresh(event.agent_id, { event });
}
