import fs from 'node:fs';
import path from 'node:path';

import { getAgentById, listAgents } from '../agents/agent-registry.js';
import type { AgentConfig } from '../agents/agent-types.js';
import { agentWorkspaceDir } from '../infra/ipc.js';
import { logger } from '../logger.js';
import { getAgentSkillScores, getSkillObservations } from '../memory/db.js';
import type {
  AgentScoreboardEntry,
  AgentSkillScore,
} from './adaptive-skills-types.js';
import type { SkillRunEvent } from './skill-run-events.js';
import { loadSkillCatalog } from './skills.js';

const GENERATED_CV_MARKER =
  '<!-- Generated by HybridClaw agent scoreboard. -->';

function displayNameForAgent(agentId: string): string {
  const agent = getAgentById(agentId);
  return agent?.displayName || agent?.name || agentId;
}

function getScoreboardAgent(agentId: string): AgentConfig | null {
  return getAgentById(agentId.trim());
}

function cvPathForAgent(agentId: string): string {
  return path.join(agentWorkspaceDir(agentId), 'CV.md');
}

function formatPercent(value: number): string {
  return `${Math.round(value * 100)}%`;
}

function formatDuration(value: number): string {
  if (value < 1_000) return `${Math.round(value)}ms`;
  return `${(value / 1_000).toFixed(1)}s`;
}

function summarizeScores(scores: AgentSkillScore[]): {
  totalExecutions: number;
  successRate: number;
  avgScore: number;
  lastObservedAt: string | null;
} {
  const totalExecutions = scores.reduce(
    (total, score) => total + score.total_executions,
    0,
  );
  const totalSuccesses = scores.reduce(
    (total, score) => total + score.success_count,
    0,
  );
  const weightedScore = scores.reduce(
    (total, score) => total + score.score * score.total_executions,
    0,
  );
  return {
    totalExecutions,
    successRate: totalExecutions > 0 ? totalSuccesses / totalExecutions : 0,
    avgScore:
      totalExecutions > 0 ? Math.round(weightedScore / totalExecutions) : 0,
    lastObservedAt:
      scores
        .map((score) => score.last_observed_at)
        .filter((value): value is string => Boolean(value))
        .sort()
        .at(-1) || null,
  };
}

export function getAgentScoreboard(): AgentScoreboardEntry[] {
  const scores = getAgentSkillScores();
  const scoresByAgent = new Map<string, AgentSkillScore[]>();
  for (const score of scores) {
    const existing = scoresByAgent.get(score.coworker_id) || [];
    existing.push(score);
    scoresByAgent.set(score.coworker_id, existing);
  }

  return [...scoresByAgent.entries()]
    .map(([agentId, agentScores]) => {
      const summary = summarizeScores(agentScores);
      return {
        coworker_id: agentId,
        display_name: displayNameForAgent(agentId),
        total_executions: summary.totalExecutions,
        success_rate: summary.successRate,
        avg_score: summary.avgScore,
        best_skills: [...agentScores]
          .sort(
            (left, right) =>
              right.score - left.score ||
              right.total_executions - left.total_executions ||
              left.skill_name.localeCompare(right.skill_name),
          )
          .slice(0, 5),
        last_observed_at: summary.lastObservedAt,
        cv_path: cvPathForAgent(agentId),
      };
    })
    .sort(
      (left, right) =>
        right.avg_score - left.avg_score ||
        right.total_executions - left.total_executions ||
        left.display_name.localeCompare(right.display_name),
    );
}

export function getBestAgentsForSkill(
  skillName: string,
  limit = 5,
): AgentSkillScore[] {
  return getAgentSkillScores({
    skillName,
    limit: Math.max(1, Math.min(limit, 25)),
  });
}

function renderCvMarkdown(input: {
  agentId: string;
  displayName: string;
  agent: AgentConfig | null;
  scores: AgentSkillScore[];
  generatedAt: string;
}): string {
  const summary = summarizeScores(input.scores);
  const topSkills = [...input.scores]
    .sort(
      (left, right) =>
        right.score - left.score ||
        right.total_executions - left.total_executions ||
        left.skill_name.localeCompare(right.skill_name),
    )
    .slice(0, 10);
  const topSkill = topSkills[0];
  const recentRuns = getSkillObservations({
    coworkerId: input.agentId,
    limit: 5,
  });
  const role = input.agent?.role?.trim() || 'Agent';
  const photo = input.agent?.imageAsset?.trim() || '';
  const lines = [
    GENERATED_CV_MARKER,
    `# ${input.displayName} CV`,
    '',
    photo ? `![${input.displayName}](${photo})` : 'Photo: not configured',
    '',
    `Agent ID: \`${input.agentId}\``,
    `Role: ${role}`,
    `Last updated: ${input.generatedAt}`,
    '',
    '## Track Record',
    '',
    `- Skill executions: ${summary.totalExecutions}`,
    `- Overall success rate: ${formatPercent(summary.successRate)}`,
    `- Average score: ${summary.avgScore}/100`,
  ];

  if (topSkill) {
    lines.push(`- Best at: ${topSkill.skill_name} (${topSkill.score}/100)`);
  }

  lines.push('', '## Skill Scores', '');
  if (topSkills.length === 0) {
    lines.push('No observed skill runs yet.');
  } else {
    for (const score of topSkills) {
      lines.push(
        `- ${score.skill_name}: ${score.score}/100, ${formatPercent(
          score.success_rate,
        )} success across ${score.total_executions} runs, avg ${formatDuration(
          score.avg_duration_ms,
        )}`,
      );
    }
  }

  lines.push('', '## Recent Track Record', '');
  if (recentRuns.length === 0) {
    lines.push('No recent skill runs yet.');
  } else {
    for (const run of recentRuns) {
      lines.push(
        `- ${run.created_at}: ${run.skill_name} ${run.outcome} in ${formatDuration(
          run.duration_ms,
        )}`,
      );
    }
  }

  return `${lines.join('\n')}\n`;
}

export function cv(
  agentId: string,
  options?: { generatedAt?: string },
): string {
  const normalizedAgentId = agentId.trim();
  if (!normalizedAgentId) {
    throw new Error('Agent id is required.');
  }
  const scores = getAgentSkillScores({ agentId: normalizedAgentId });
  const displayName = displayNameForAgent(normalizedAgentId);
  return renderCvMarkdown({
    agentId: normalizedAgentId,
    displayName,
    agent: getScoreboardAgent(normalizedAgentId),
    scores,
    generatedAt: options?.generatedAt || new Date().toISOString(),
  });
}

export function refreshAgentCv(agentId: string): string | null {
  const normalizedAgentId = agentId.trim();
  if (!normalizedAgentId) return null;
  const cvPath = cvPathForAgent(normalizedAgentId);
  fs.mkdirSync(path.dirname(cvPath), { recursive: true });
  fs.writeFileSync(cvPath, cv(normalizedAgentId), 'utf-8');
  return cvPath;
}

export function refreshAgentCvForSkillRun(event: SkillRunEvent): void {
  if (!event.coworker_id) return;
  try {
    refreshAgentCv(event.coworker_id);
  } catch (error) {
    logger.warn(
      {
        agentId: event.coworker_id,
        skillId: event.skill_id,
        runId: event.run_id,
        error,
      },
      'Failed to refresh agent CV',
    );
  }
}

export function refreshAllAgentCvs(): string[] {
  const registeredIds = listAgents().map((agent) => agent.id);
  const observedIds = getAgentScoreboard().map((entry) => entry.coworker_id);
  const ids = Array.from(new Set([...registeredIds, ...observedIds]));
  return ids
    .map((id) => refreshAgentCv(id))
    .filter((value): value is string => Boolean(value));
}

function normalizeRecommendationTerm(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function scoreSkillForTask(params: {
  task: string;
  skillName: string;
  description: string;
  category: string;
  tags: string[];
}): number {
  const task = normalizeRecommendationTerm(params.task);
  if (!task) return 0;
  const haystack = normalizeRecommendationTerm(
    [
      params.skillName,
      params.description,
      params.category,
      ...params.tags,
    ].join(' '),
  );
  const skillName = normalizeRecommendationTerm(params.skillName);
  let score = 0;
  if (task.includes(skillName) || haystack.includes(task)) score += 10;
  for (const term of task.split(' ')) {
    if (term.length < 3) continue;
    if (skillName.includes(term)) score += 4;
    if (haystack.includes(term)) score += 1;
  }
  return score;
}

export interface AgentRecommendation {
  agent_id: string;
  display_name: string;
  skill_id: string;
  quality_score: number;
  success_rate: number;
  total_executions: number;
  relevance_score: number;
  rank_score: number;
}

export function recommendAgentsFor(
  task: string,
  limit = 3,
): AgentRecommendation[] {
  const skills = loadSkillCatalog();
  const relevanceBySkill = new Map<string, number>();
  for (const skill of skills) {
    const relevance = scoreSkillForTask({
      task,
      skillName: skill.name,
      description: skill.description,
      category: skill.category,
      tags: skill.metadata.hybridclaw.tags,
    });
    if (relevance > 0) relevanceBySkill.set(skill.name, relevance);
  }

  const scores = getAgentSkillScores();
  return scores
    .map((score) => {
      const relevance = relevanceBySkill.get(score.skill_id) || 0;
      return {
        agent_id: score.coworker_id,
        display_name: displayNameForAgent(score.coworker_id),
        skill_id: score.skill_id,
        quality_score: score.quality_score,
        success_rate: score.success_rate,
        total_executions: score.total_executions,
        relevance_score: relevance,
        rank_score: relevance * 100 + score.quality_score,
      };
    })
    .filter((entry) => entry.relevance_score > 0)
    .sort(
      (left, right) =>
        right.rank_score - left.rank_score ||
        right.quality_score - left.quality_score ||
        right.total_executions - left.total_executions ||
        left.display_name.localeCompare(right.display_name),
    )
    .slice(0, Math.max(1, Math.min(limit, 10)));
}

export function formatAgentAssignmentHints(task: string): string {
  const recommendations = recommendAgentsFor(task, 3);
  if (recommendations.length === 0) return '';
  return [
    '## Agent Assignment Hints',
    ...recommendations.map(
      (entry, index) =>
        `${index + 1}. ${entry.display_name} (${entry.agent_id}) for ${entry.skill_id}: ${entry.quality_score}/100 quality, ${formatPercent(entry.success_rate)} success across ${entry.total_executions} runs.`,
    ),
  ].join('\n');
}
