import fs from 'node:fs';
import path from 'node:path';

import { getAgentById, listAgents } from '../agents/agent-registry.js';
import { agentWorkspaceDir } from '../infra/ipc.js';
import { logger } from '../logger.js';
import { getCoworkerSkillScores } from '../memory/db.js';
import type {
  CoworkerScoreboardEntry,
  CoworkerSkillScore,
} from './adaptive-skills-types.js';
import type { SkillRunEvent } from './skill-run-events.js';

const GENERATED_CV_MARKER =
  '<!-- Generated by HybridClaw coworker scoreboard. -->';

function displayNameForCoworker(coworkerId: string): string {
  const agent = getAgentById(coworkerId);
  return agent?.displayName || agent?.name || coworkerId;
}

function cvPathForCoworker(coworkerId: string): string {
  return path.join(agentWorkspaceDir(coworkerId), 'CV.md');
}

function formatPercent(value: number): string {
  return `${Math.round(value * 100)}%`;
}

function formatDuration(value: number): string {
  if (value < 1_000) return `${Math.round(value)}ms`;
  return `${(value / 1_000).toFixed(1)}s`;
}

function summarizeScores(scores: CoworkerSkillScore[]): {
  totalExecutions: number;
  successRate: number;
  avgScore: number;
  lastObservedAt: string | null;
} {
  const totalExecutions = scores.reduce(
    (total, score) => total + score.total_executions,
    0,
  );
  const totalSuccesses = scores.reduce(
    (total, score) => total + score.success_count,
    0,
  );
  const weightedScore = scores.reduce(
    (total, score) => total + score.score * score.total_executions,
    0,
  );
  return {
    totalExecutions,
    successRate: totalExecutions > 0 ? totalSuccesses / totalExecutions : 0,
    avgScore:
      totalExecutions > 0 ? Math.round(weightedScore / totalExecutions) : 0,
    lastObservedAt:
      scores
        .map((score) => score.last_observed_at)
        .filter((value): value is string => Boolean(value))
        .sort()
        .at(-1) || null,
  };
}

export function getCoworkerScoreboard(): CoworkerScoreboardEntry[] {
  const scores = getCoworkerSkillScores();
  const scoresByCoworker = new Map<string, CoworkerSkillScore[]>();
  for (const score of scores) {
    const existing = scoresByCoworker.get(score.coworker_id) || [];
    existing.push(score);
    scoresByCoworker.set(score.coworker_id, existing);
  }

  return [...scoresByCoworker.entries()]
    .map(([coworkerId, coworkerScores]) => {
      const summary = summarizeScores(coworkerScores);
      return {
        coworker_id: coworkerId,
        display_name: displayNameForCoworker(coworkerId),
        total_executions: summary.totalExecutions,
        success_rate: summary.successRate,
        avg_score: summary.avgScore,
        best_skills: [...coworkerScores]
          .sort(
            (left, right) =>
              right.score - left.score ||
              right.total_executions - left.total_executions ||
              left.skill_name.localeCompare(right.skill_name),
          )
          .slice(0, 5),
        last_observed_at: summary.lastObservedAt,
        cv_path: cvPathForCoworker(coworkerId),
      };
    })
    .sort(
      (left, right) =>
        right.avg_score - left.avg_score ||
        right.total_executions - left.total_executions ||
        left.display_name.localeCompare(right.display_name),
    );
}

export function getBestCoworkersForSkill(
  skillName: string,
  limit = 5,
): CoworkerSkillScore[] {
  return getCoworkerSkillScores({
    skillName,
    limit: Math.max(1, Math.min(limit, 25)),
  });
}

function renderCvMarkdown(input: {
  coworkerId: string;
  displayName: string;
  scores: CoworkerSkillScore[];
}): string {
  const summary = summarizeScores(input.scores);
  const topSkills = [...input.scores]
    .sort(
      (left, right) =>
        right.score - left.score ||
        right.total_executions - left.total_executions ||
        left.skill_name.localeCompare(right.skill_name),
    )
    .slice(0, 10);
  const topSkill = topSkills[0];
  const lines = [
    GENERATED_CV_MARKER,
    `# ${input.displayName} CV`,
    '',
    `Coworker ID: \`${input.coworkerId}\``,
    `Last updated: ${new Date().toISOString()}`,
    '',
    '## Track Record',
    '',
    `- Skill executions: ${summary.totalExecutions}`,
    `- Overall success rate: ${formatPercent(summary.successRate)}`,
    `- Average score: ${summary.avgScore}/100`,
  ];

  if (topSkill) {
    lines.push(`- Best at: ${topSkill.skill_name} (${topSkill.score}/100)`);
  }

  lines.push('', '## Skill Scores', '');
  if (topSkills.length === 0) {
    lines.push('No observed skill runs yet.');
  } else {
    for (const score of topSkills) {
      lines.push(
        `- ${score.skill_name}: ${score.score}/100, ${formatPercent(
          score.success_rate,
        )} success across ${score.total_executions} runs, avg ${formatDuration(
          score.avg_duration_ms,
        )}`,
      );
    }
  }

  return `${lines.join('\n')}\n`;
}

export function refreshCoworkerCv(coworkerId: string): string | null {
  const normalizedCoworkerId = coworkerId.trim();
  if (!normalizedCoworkerId) return null;
  const scores = getCoworkerSkillScores({ coworkerId: normalizedCoworkerId });
  const displayName = displayNameForCoworker(normalizedCoworkerId);
  const cvPath = cvPathForCoworker(normalizedCoworkerId);
  fs.mkdirSync(path.dirname(cvPath), { recursive: true });
  fs.writeFileSync(
    cvPath,
    renderCvMarkdown({
      coworkerId: normalizedCoworkerId,
      displayName,
      scores,
    }),
    'utf-8',
  );
  return cvPath;
}

export function refreshCoworkerCvForSkillRun(event: SkillRunEvent): void {
  if (!event.coworker_id) return;
  try {
    refreshCoworkerCv(event.coworker_id);
  } catch (error) {
    logger.warn(
      {
        coworkerId: event.coworker_id,
        skillId: event.skill_id,
        runId: event.run_id,
        error,
      },
      'Failed to refresh coworker CV',
    );
  }
}

export function refreshAllCoworkerCvs(): string[] {
  const registeredIds = listAgents().map((agent) => agent.id);
  const observedIds = getCoworkerScoreboard().map((entry) => entry.coworker_id);
  const ids = Array.from(new Set([...registeredIds, ...observedIds]));
  return ids
    .map((id) => refreshCoworkerCv(id))
    .filter((value): value is string => Boolean(value));
}
