import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

// Importing the runtime schema also loads secret-store helpers. Point those
// helpers at an isolated, non-existent temp directory so registry generation
// never inspects or chmods an operator's real runtime home.
process.env.HYBRIDCLAW_DATA_DIR = '/tmp/hybridclaw-runtime-home';

const { DEFAULT_RUNTIME_CONFIG } = await import(
  '../src/config/runtime-config.js'
);

type SettingKind = 'boolean' | 'number' | 'string' | 'list' | 'object';

interface GeneratedSetting {
  path: string;
  section: string;
  kind: SettingKind;
  defaultValue: unknown;
}

function settingKind(value: unknown): SettingKind {
  if (Array.isArray(value)) return 'list';
  if (value !== null && typeof value === 'object') return 'object';
  if (typeof value === 'boolean') return 'boolean';
  if (typeof value === 'number') return 'number';
  return 'string';
}

function collectSettings(
  value: unknown,
  pathParts: string[],
  output: GeneratedSetting[],
): void {
  const record =
    value !== null && typeof value === 'object' && !Array.isArray(value)
      ? (value as Record<string, unknown>)
      : null;
  const isStoredSecretRef =
    record?.source === 'store' && typeof record.id === 'string';
  if (Array.isArray(value) || value === null || typeof value !== 'object') {
    output.push({
      path: pathParts.join('.'),
      section: pathParts[0] ?? '',
      kind: settingKind(value),
      defaultValue: value,
    });
    return;
  }

  if (isStoredSecretRef) {
    output.push({
      path: pathParts.join('.'),
      section: pathParts[0] ?? '',
      kind: 'object',
      defaultValue: value,
    });
    return;
  }

  const entries = Object.entries(record ?? {});
  if (entries.length === 0) {
    output.push({
      path: pathParts.join('.'),
      section: pathParts[0] ?? '',
      kind: 'object',
      defaultValue: value,
    });
    return;
  }

  for (const [key, child] of entries) {
    collectSettings(child, [...pathParts, key], output);
  }
}

function buildRegistry(): GeneratedSetting[] {
  const settings: GeneratedSetting[] = [];
  for (const [section, value] of Object.entries(DEFAULT_RUNTIME_CONFIG)) {
    collectSettings(value, [section], settings);
  }
  settings.sort((left, right) => left.path.localeCompare(right.path));
  return settings;
}

function renderRegistry(settings: ReadonlyArray<GeneratedSetting>): string {
  return `// Generated by scripts/generate-settings-registry.ts. Do not edit.\n\nexport type GeneratedSettingKind =\n  | 'boolean'\n  | 'number'\n  | 'string'\n  | 'list'\n  | 'object';\n\nexport interface GeneratedSettingEntry {\n  path: string;\n  section: string;\n  kind: GeneratedSettingKind;\n  defaultValue: unknown;\n}\n\nexport const GENERATED_SETTINGS_REGISTRY: ReadonlyArray<GeneratedSettingEntry> = ${JSON.stringify(settings, null, 2)};\n`;
}

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const outputPath = path.join(
  repoRoot,
  'console/src/generated/settings-registry.ts',
);
const settings = buildRegistry();
const generated = renderRegistry(settings);

if (process.argv.includes('--check')) {
  const current = fs.existsSync(outputPath)
    ? ((await import(`${pathToFileURL(outputPath).href}?check=${Date.now()}`))
        .GENERATED_SETTINGS_REGISTRY as unknown)
    : null;
  if (JSON.stringify(current) !== JSON.stringify(settings)) {
    console.error(
      'Settings registry is stale. Run `npm run generate:settings-registry`.',
    );
    process.exitCode = 1;
  }
} else {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, generated);
  console.log(`Generated ${path.relative(repoRoot, outputPath)}.`);
}
